name: Github Actions for Lab 14
run-name: ${{ github.actor }} is checking Lab 14 for pre-defined compliance and general issues
on: [push]
jobs:
  Check-For-NPM-ISSUES:
    runs-on: ubuntu-latest
    env:
      working-directory-insecure: ./insecure
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: (cd insecure && npm install)
      - run: echo "NPM is now checking for vulnerabilities"
      - run: (cd insecure && npm audit)
  Check-For-Messed-Up-JS:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: (cd mashup && npm install)
      - name: Check our linter for errors
        run: (cd mashup && npm run lint)



