name: Github Actions for Lab 14
run-name: ${{ github.actor }} is checking Lab 14 for pre-defined compliance and general issues
on: [push]
jobs:
  Check-For-NPM-ISSUES:
    runs-on: ubuntu-latest
    env:
      working-directory-insecure: ./insecure
    steps:
      - run: npm install
        working-directory: ${{env.working-directory-insecure}}
      - run: echo "NPM is now checking for vulnerabilities"
      - run: npm audit
        working-directory: ${{env.working-directory-insecure}}

